font/Manual-Do-Crescer/Models/ErrorViewModel.cs
namespace Manual_Do_Crescer.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

font/Manual-Do-Crescer/Models/Pais.cs
namespace Manual_Do_Crescer.Models
{
    public class Pais : Usuario
    {

    }
}

font/Manual-Do-Crescer/Models/Profissional.cs
namespace Manual_Do_Crescer.Models
{
    public class Profissional : Usuario
    {
    }
}

font/Manual-Do-Crescer/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Manual_Do_Crescer.Models
{
    [Table("Usuario")]
    public class Usuario
    {
        [Key]
        [Display(Name = "Código")]
        [Column("Id")]
        public int id { get; set; }

        [Display(Name = "Nome")]
        [Column("Nome")]
        public string nome { get; set; }

        [Display(Name = "Email")]
        [Column("Email")]
        public string email { get; set; }

        [Display(Name = "Senha")]
        [Column("Senha")]
        public string senha { get; set; }

        [Display(Name = "Telefone")]
        [Column("Telefone")]
        public string telefone { get; set; }

        [Display(Name = "Tipo de Usuário")]
        [Column("TipoUsuario")]
        public string tipoUsuario { get; set; }
    }
}

font/Manual-Do-Crescer/Controllers/HomeController.cs
using Manual_Do_Crescer.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Manual_Do_Crescer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Servicos()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

font/Manual-Do-Crescer/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Manual_Do_Crescer.Data;
using Manual_Do_Crescer.Models;
using Manual_Do_Crescer.ViewModel;

namespace Manual_Do_Crescer.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly Contexto _context;

        public UsuariosController(Contexto context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuario.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        /* Método para Registrar */
        public async Task<IActionResult> Create([Bind("id,nome,email,senha,telefone,tipoUsuario")] Usuario usuario)
        {
            Console.WriteLine("tipoUsuario: ", usuario.tipoUsuario);

            if (ModelState.IsValid)
            {
                switch (usuario.tipoUsuario)
                {
                    case "pais":
                        _context.Add(new Pais { nome = usuario.nome, email = usuario.email, senha = usuario.senha, telefone = usuario.telefone, tipoUsuario = usuario.tipoUsuario });
                        break;
                    case "profissional":
                        _context.Add(new Profissional { nome = usuario.nome, email = usuario.email, senha = usuario.senha, telefone = usuario.telefone, tipoUsuario = usuario.tipoUsuario });
                        break;
                    default:
                        return BadRequest("Tipo de usuário inválido.");
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }
        /*Método para Login */
        public async Task<IActionResult> Login(LoginViewModel login)
        {
            if (ModelState.IsValid)
            {
                var usuario = await _context.Usuario.FirstOrDefaultAsync(u => u.email == login.email && u.senha == login.senha);

                if (usuario != null)
                {
                    // Autenticar usuário (por exemplo, definindo cookies de autenticação)
                    // Redirecionar para a página principal ou para a página de perfil do usuário
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Credenciais inválidas. Por favor, tente novamente.");
                    return View(login);
                }
            }

            return View(login);
        }


        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nome,email,senha,telefone")] Usuario usuario)
        {
            if (id != usuario.id)
            {
                return NotFound();
            }



            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuario.Remove(usuario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuario.Any(e => e.id == id);
        }
    }
}

font/Manual-Do-Crescer/Views/Home/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bibliotecas -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <link rel="stylesheet" href="~/css/cadastro.css">
    <link rel="shortcut icon" href="favicon.png" type="image/x-icon">
    <title>Cadastre-se</title>
</head>

<body>
    <!--Header-->
    <header>
        <nav class="navbar navbar-expand-lg navigation-wrap">
            <div class="container">
                <a class="navbar-brand" href="./index.html"><img src="~/images/img/logo.svg" alt=""></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-stream navbar-toggler-icon"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav navbar-padding ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Servicos">Serviços</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Login">Sign In/Out</a>
                        </li>
                        <a href="#">
                            <li class="nav-item">
                                <button class="main-btn">IR PARA O MANUAL</button>
                            </li>
                        </a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <!--Formulário-->
    <div class="alavanque-bg">
        <main id="alavanque container" class="js-scroll">
            <!--Titulo da página-->
            <div class="titulo container">
                <h3 style="position: relative; font-size: 24px; color: #190038; left: 4px;">O PRIMEIRO PASSO!</h3>
                <h1 style="font-weight: bold; font-size: 60px; color: #190038;">Cadastre-se</h1>
            </div>
            <!--Abas-->
            <div class="user-type">
                <div class="pais" id="paisBtn" onclick="selecionarAba(this)">
                    <button class="user-type-button">
                        Pais e Mães
                        <img src="images/icones/seta-aba.svg" alt="" class="seta-aba" id="setaPais">
                    </button>
                </div>
                <div class="profissional" id="profissionalBtn" onclick="selecionarAba(this)">
                    <button class="user-type-button">
                        Profissional
                        <img src="images/icones/seta-aba.svg" alt="" class="seta-aba" id="setaProfissional">
                    </button>
                </div>
            </div>
            <!--Conteúdo das abas-->
            <div class="contato container fadeInUp" data-anime="800">
                <!--Login-->
                <section class="contato-dados" aria-label="Endereço">
                    <h2 style="font-weight: bold; text-align: center; color: #003B4E;">Já possui cadastro?</h2>
                    <form method="post" asp-action="Login" asp-controller="Usuarios" class="user-login">
                        <div class="user-email">
                            <input type="email" name="" id="input-login" autocomplete="off" placeholder="Email" />
                        </div>

                        <div class="user-senha">
                            <input type="password" name="" id="input-login" autocomplete="off" placeholder="Senha">
                        </div>
                        <div class="button-login">
                            <button>FAZER LOGIN</button>
                        </div>
                        <p class="alter-login">ou faça login com</p>
                    </form>
                    <!--Cadastro-->
                    <div class="contato-redes">
                        <a href="./">
                            <img src="~/images/icones/google.svg">
                        </a>
                        <a href="./">
                            <img src="~/images/icones/facebook.svg">
                        </a>
                        <a href="./">
                            <img src="~/images/icones/instagram.svg">
                        </a>
                    </div>
                </section>
                <section aria-label="Formulário" class="contato-formulario">
                    <h2 style="font-weight: bold; color: rgba(255, 255, 255, 0.884);; margin-bottom: 40px; text-align: center;" class="titleForm">Cadastro</h2>
                    <form class="form" id="formCadastro" method="post" asp-controller="Usuarios" asp-action="Create">
                        <input type="hidden" id="tipoUsuario" name="tipoUsuario" value="pais" />
                        <div>
                            <label for="nome">Nome</label>
                            <input type="text" id="nome" name="nome" placeholder="Seu Nome" autocomplete="off">
                        </div>
                        <div>
                            <label for="nome">Telefone</label>
                            <input type="text" id="Telefone" name="telefone" placeholder="(31) 99999-9999" autocomplete="off">
                        </div>
                        <div class="col-2">
                            <label for="nome">Email</label>
                            <input type="email" id="Email" name="email" placeholder="contato@email.com" autocomplete="off">
                        </div>
                        <div class="col-2">
                            <label for="nome">Senha</label>
                            <input type="password" name="senha" id="Senha">
                        </div>
                        <div class="button-cadastro">
                            <button type="submit" class="blue-btn-form mt-5" id="btnCadastro">CADASTRAR<span><img
                                        src="~/images/icones/bebe-feliz.svg" alt=""></span></button>
                        </div>
                    </form>
                </section>
            </div>
        </main>
    </div>
    <!--Footer-->
    <footer id="footer">
        <div class="footer py-5">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <a class="footer-link" href="#">Home</a>
                        <a class="footer-link" href="#">Saiba Mais</a>
                        <a class="footer-link" href="#">Ajude-nos</a>
                        <a class="footer-link" href="#">Cadastrar</a>
                        <div class="footer-social pt-4 text-center">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="footer-copy">
                            <div class="copy-right text-center pt-5">
                                <p class="">© 2024 Manual do Crescer. Todos os direitos reservados. </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- JS Libraries -->
    @* <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
    <!-- JS Próprio -->
    <script src="~/js/plugins/simple-anime.js"></script>
    <script src="~/js/cadastro.js"></script>
    <script src="~/js/main.js"></script>

</body>

</html>

font/Manual-Do-Crescer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Manual_Do_Crescer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Manual_Do_Crescer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Manual_Do_Crescer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios Cadastrados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Manual_Do_Crescer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

font/Manual-Do-Crescer/Views/Usuarios/Create.cshtml
@model Manual_Do_Crescer.Models.Usuario

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="senha" class="control-label"></label>
                <input asp-for="senha" class="form-control" />
                <span asp-validation-for="senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

font/Manual-Do-Crescer/Views/Usuarios/Delete.cshtml
@model Manual_Do_Crescer.Models.Usuario

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.senha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.senha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

font/Manual-Do-Crescer/Views/Usuarios/Details.cshtml
@model Manual_Do_Crescer.Models.Usuario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.senha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.senha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

font/Manual-Do-Crescer/Views/Usuarios/Edit.cshtml
@model Manual_Do_Crescer.Models.Usuario

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="senha" class="control-label"></label>
                <input asp-for="senha" class="form-control" />
                <span asp-validation-for="senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

font/Manual-Do-Crescer/Views/Usuarios/Index.cshtml
@model IEnumerable<Manual_Do_Crescer.Models.Usuario>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.senha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tipoUsuario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.senha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tipoUsuario)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>